---
- name: Checking for Rust and Installing if Absent
  hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: Update Repositories
      ansible.builtin.apt: 
      update_cache: yes
      become_user: root
      changed_when: false
  vars:
    user: "{{ ansible_user_id }}"
  tasks:
    - name: Check If Cargo Is Installed
      ansible.builtin.shell: command -v cargo
      register: cargo_exists
      ignore_errors: true

    - name: Download Installer
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: Install Rust/Cargo
      when: cargo_exists is failed
      ansible.builtin.shell: /tmp/sh.rustup.rs -y
      tags:
        - rust
